# Generated by Django 6.0.4 on 2026-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
            options={
                'db_table': 'appReclamos_registro',
            },
        ),
    ]
